#! /usr/bin/env python

import os, sys, shutil, subprocess

nodes = ["beef"]

# Update the file list from beef
files = []
for node in nodes:
    listf = subprocess.Popen(["ssh",node,"/home/pulsar64/src/guppi_combine/find_guppi_files"], stdout=subprocess.PIPE)
    for line in listf.stdout.readlines():
        files += [line.rstrip()]

# Copy files from beef
basedir = "/lustre/pulsar/scratch/GUPPI"
for f in files:
    (fname_full,proj) = f.split()
    fname = fname_full.split('/')[-1]
    outdir = basedir + "/" + proj
    print outdir
    sys.stdout.flush()
    try:
        os.makedirs(outdir)
    except:
        # This is to catch the 'directory already exists' error.
        # Should make it more selective.
        pass
    if os.path.exists(outdir + "/" + fname):
        print fname + " exists, skipping."
        continue
    # Grab file from beef
    cmd = ["rsync", "-avP", "beef::"+fname_full.lstrip('/'), outdir+"/"]
    print cmd
    sys.stdout.flush()
    subprocess.call(cmd)
