#! /usr/bin/env python

import os, sys, shutil, subprocess

nodes = ["gpu1-10", "gpu2-10", "gpu3-10", "gpu4-10", "gpu5-10", "gpu6-10",
        "gpu7-10", "gpu8-10", "gpu9-10"]

# Update the file list from each node
files = []
for node in nodes:
    listf = subprocess.Popen(["ssh",node,"select_files -s -M -O name,projid -p 12B_320 -t PSR -t CAL"], stdout=subprocess.PIPE)
    for line in listf.stdout.readlines():
        files += [line.rstrip()]

# Get the unique list
files = list(set(files))

# Handle all the cases that seem to appear in /home/archive/science-data
# Not sure what to do about test data
def projid_to_dir(projid):
    m = re.match(r"AGBT(\d{2}[ABC])",projid)
    if m:
        return "science-data/" + m.group(1)
    if re.match(r"AGLST",projid):
        return "science-data/Fermi"
    if re.match(r"ACH",projid):
        return "science-data/Chandra"
    if re.match(r"AB",projid):
        return "science-data/VLBA"
    if re.match(r"AG",projid):
        return "science-data/GlobalVLBI"
    return "science-data/other"

# Call combine on each
basedir = "/lustre/pulsar/scratch/GUPPI2"
for f in files:
    (fname,proj) = f.split()
    # Skip test projects for now
    if proj[0]=='T': continue
    outdir = basedir + "/" + projid_to_dir(proj) + "/" + proj + "/GUPPI"
    print outdir
    sys.stdout.flush()
    try:
        os.makedirs(outdir)
    except:
        # This is to catch the 'directory already exists' error.
        # Should make it more selective.
        pass
    if os.path.exists(outdir + "/" + fname):
        print fname + " exists, skipping."
        continue
    # Output file to /dev/shm then move it to avoid 
    # cfitsio and psrchive buffering/write patterns
    # going really slow on lustre..
    cmd = ["guppi_combine","-v","-T","-O","/dev/shm",fname]
    print cmd
    sys.stdout.flush()
    subprocess.call(cmd)
    print "guppi2_update_all: moving '" + fname + "' to '" + outdir + "'"
    sys.stdout.flush()
    try:
        shutil.move("/dev/shm/" + fname, outdir + "/" + fname)
    except:
        print "guppi2_update_all: error processing '" + fname + "'"
    # Make sure stuff does not accumulate in /dev/shm
    os.system("rm /dev/shm/gpu?/guppi*.fits")
